- name: Reading secrets from vault 
  hosts: localhost
  tasks:  
    - name: Reading secret 
      ansible.builtin.debug: 
        msg: "{{SEC.MYSQL_PASS}}"
      vars:
        SEC: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=expense-dev/data/backend token={{token}} url=https://vaults.expense.internal:8200 validate_certs=False') }}"